name: flutter_template
description: Flutter 项目模板
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ">=0.1.2 <2.0.0"

  # 常用工具库
  flustars: ">=0.2.6+1 <3.0.0"

  # 屏幕适配
  flutter_screenutil: ">=0.6.0 <6.0.0"

  # APP相关
  ## 设备信息
  device_info: ">=0.4.0+3 <3.0.0"

  ## 包信息
  package_info: ">=0.4.0+6 <3.0.0"

  ## 打开其他 APP
  url_launcher: ">=5.1.4 <7.0.0"

  # 网络请求
  dio: ">=3.0.3 <6.0.0"
  dio_cookie_manager: any
  cookie_jar: any

  ## 数据状态管理
  provider: ">=3.1.0 <7.0.0"
  mobx: any
  flutter_mobx: any
  # mobx_codegen:
  # flutter_svg:
  path_provider: any
  cached_network_image: any
  shimmer: any

  ## 注解相关
  json_annotation: ">=3.0.0 <5.0.0"
  functional_widget_annotation: ">=0.5.1 <0.11.0"

  # 提示层
  oktoast: ">=2.2.0 <4.0.0"

  ## 下拉刷新
  pull_to_refresh: ">=1.5.6 <3.0.0"

  ## 幻灯片
  flutter_swiper: ^1.1.6

  ## 动画
  flare_flutter: any

  ## 图表
  syncfusion_flutter_charts: ">=17.3.14 <21.0.0"
  flutter_sparkline: any

builders:
  functional_widget:
  json_serializable:

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  
  ## 格式化
  intl: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/flare/

fonts:
  - family: SpaceMonoRegular
    fonts:
      - asset: assets/fonts/SpaceMono-Regular.ttf
  - family: SpaceMonoBold
    fonts:
      - asset: assets/fonts/SpaceMono-Bold.ttf
  - family: RobotoCondensedBold
    fonts:
      - asset: assets/fonts/RobotoCondensed-Bold.ttf
  - family: RobotoRegular
    fonts:
      - asset: assets/fonts/Roboto-Regular.ttf
  - family: MontserratMedium
    fonts:
      - asset: assets/fonts/Montserrat-Medium.otf
  - family: MontserratRegular
    fonts:
      - asset: assets/fonts/Montserrat-Regular.otf
  - family: MontserratBold
    fonts:
      - asset: assets/fonts/Montserrat-Bold.otf
